[package]
name = "net-tools"
version = "0.1.0"
edition = "2021"

[lib]
name = "net-tools"
path = "lib/lib.rs"

[[bin]]
name = "cert-checker"
path = "src/cert_checker.rs"

[dependencies]
rustls = { version = "0.21", features = ["dangerous_configuration", "secret_extraction"] }
x509-cert = "0.2"
